# If your SonarQube Cloud organization key is different, replace sonar.organization.
sonar.organization=ayoub-hm
sonar.projectKey=Ayoub-HM_TP2_Pipeline-DevSecOps-avec-GitHub-Actions
sonar.projectName=TP2 Pipeline DevSecOps avec GitHub Actions
sonar.sources=src,nginx,.github/workflows
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/*.min.js
